// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeIntroController from "./home_intro_controller"
application.register("home-intro", HomeIntroController)

import SearchbarController from "./searchbar_controller"
application.register("searchbar", SearchbarController)

import TweetController from "./tweet_controller"
application.register("tweet", TweetController)
