meta_product_name: "Parley"
meta_title: "Parley - Open our mind"
meta_description: "A new digital bridge across our divided societies"
meta_image: "cover.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards